export interface CustomerCardModel{
    CustId:any;
    TransactionDate:any;
    PreviousBalance:any;
    PointsEarned:any;
    PointsRedeemed:any;
    RedemptionChoice:any;
    NewBalance:Number;
    AmountRedeemed:Number;
    ExpiryDate:Date;
    AvailableAmount:Number;
    RemainingPoints:Number;
    OpeningBalance:Number;
    EarnedPoints:Number;
    RedeemedPoints:Number;
    ClosingBalance:Number;
    Amount:Number;
    FirstName:Number;
    LastName:Number;
    CardNumber:Number;
    Card_Type:Number;
    Transaction_Type:Number;
    StartDate:Date;
    EndDate:Date;
}